sudo: required
dist: trusty
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install libopenblas-dev
  - sudo apt-get install liblapack-dev
  - git clone https://github.com/SGL-UT/GPSTk.git
  - cd GPSTk
  - ./build.sh -b build -e -x
  - export GPSTK_SRC=$(pwd)
  - export GPSTK_BUILD=$(pwd)/build
  - cd ..
  - pip install -r requirements.txt
script:
  - python setup.py build
