sudo: required
dist: trusty
language: python
python:
  - "2.7"
before_install:
  - git clone https://github.com/SGL-UT/GPSTk.git
  - cd GPSTk
  - ./build.sh -e -x
  - cd ..
  - export GPSTK_SRC=$HOME/GPSTk
  - export GPSTK_BUILD=$HOME/GPSTk/build
  - pip install -r requirements.txt
script:
  - python setup.py build
